# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainGui(object):
    def setupUi(self, mainGui):
        mainGui.setObjectName("mainGui")
        mainGui.setEnabled(True)
        mainGui.resize(741, 401)
        mainGui.setWindowOpacity(8.0)
        mainGui.setAutoFillBackground(False)
        mainGui.setStyleSheet("background-color: rgb(0,0,0);")
        self.label = QtWidgets.QLabel(mainGui)
        self.label.setGeometry(QtCore.QRect(0, 10, 741, 211))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo.png"))
        self.label.setObjectName("label")
        self.start = QtWidgets.QPushButton(mainGui)
        self.start.setEnabled(True)
        self.start.setGeometry(QtCore.QRect(80, 250, 241, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(22)
        font.setBold(True)
        self.start.setFont(font)
        self.start.setAutoFillBackground(False)
        self.start.setStyleSheet("alternate-background-color: rgb(255, 170, 0);")
        icon = QtGui.QIcon.fromTheme("dialog-information")
        self.start.setIcon(icon)
        self.start.setCheckable(False)
        self.start.setObjectName("start")
        self.end = QtWidgets.QPushButton(mainGui)
        self.end.setEnabled(True)
        self.end.setGeometry(QtCore.QRect(410, 250, 241, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(22)
        font.setBold(True)
        self.end.setFont(font)
        self.end.setStyleSheet("alternate-background-color: rgb(255, 170, 0);")
        icon = QtGui.QIcon.fromTheme("dialog-information")
        self.end.setIcon(icon)
        self.end.setCheckable(False)
        self.end.setObjectName("end")

        self.retranslateUi(mainGui)
        QtCore.QMetaObject.connectSlotsByName(mainGui)

    def retranslateUi(self, mainGui):
        _translate = QtCore.QCoreApplication.translate
        mainGui.setWindowTitle(_translate("mainGui", "mainGui"))
        self.start.setText(_translate("mainGui", "START "))
        self.end.setText(_translate("mainGui", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainGui = QtWidgets.QWidget()
    ui = Ui_mainGui()
    ui.setupUi(mainGui)
    mainGui.show()
    sys.exit(app.exec_())
